name: qr_machine_scanner
description: QR Machine Scanner

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^7.1.1
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.9.3
  awesome_dialog: ^3.1.2
  mime: ^1.0.5
  cherry_toast: ^1.10.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.1.3
  themed: ^6.0.0
  path_provider: ^2.1.5
  qr_code_scanner_plus: ^2.0.10+1
  mobile_scanner: ^7.0.0-beta.7
  image_picker: ^1.1.2
  http: ^1.3.0
  file_picker: ^9.0.2
  gallery_saver_plus: ^3.2.4
  flutter_pdfview: ^1.4.0
  flutter_markdown: ^0.7.6+2
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  test: ^1.19.0
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"